#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');

const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4021';
const LORA = process.env.LORA_URL || 'https://lora.algokit.io/transaction';

async function fetchJob(jobId) {
  const res = await fetch(`${API}/agent/jobs/${jobId}`);
  if (!res.ok) throw new Error(`Failed to fetch job ${jobId}: ${res.status}`);
  return res.json();
}

function writeLine(doc, text, opts = {}) {
  doc.fontSize(opts.size || 10).text(text, { continued: false });
}

async function main() {
  const jobId = process.argv[2];
  const out = process.argv[3] || `job-${jobId}-receipt.pdf`;
  if (!jobId) {
    console.error('Usage: generate-receipt.js <jobId> [out.pdf]');
    process.exit(2);
  }

  const job = await fetchJob(jobId);

  const doc = new PDFDocument({ margin: 40 });
  const stream = fs.createWriteStream(out);
  doc.pipe(stream);

  doc.fontSize(16).text(`PackRoute Agent — Job Receipt`, { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(10).text(`Job ID: ${job.id}`);
  doc.text(`Status: ${job.status}`);
  doc.text(`Created: ${job.created_at ?? ''}`);
  doc.moveDown(0.5);

  doc.fontSize(12).text('Steps:', { underline: true });
  doc.moveDown(0.25);
  (job.steps || []).forEach((s) => {
    doc.fontSize(10).text(`- ${s.label} — ${s.status}`);
    if (s.detail) doc.fontSize(9).fillColor('gray').text(`  ${s.detail}`);
    if (s.tx_id) {
      doc.fillColor('blue').text(`  Tx: ${LORA}/${s.tx_id}`, { link: `${LORA}/${s.tx_id}` });
      doc.fillColor('black');
    }
  });

  doc.moveDown(0.5);
  doc.fontSize(12).text('Payments / Spends:', { underline: true });
  doc.moveDown(0.25);
  (job.spends || []).forEach((p) => {
    const demo = p.demo ? ' (demo)' : '';
    doc.fontSize(10).text(`- ${p.endpoint.split('?')[0]} — $${(p.amount_usd||0).toFixed(2)}${demo}`);
    if (p.tx_id) doc.fillColor('blue').text(`  Tx: ${LORA}/${p.tx_id}`, { link: `${LORA}/${p.tx_id}` }).fillColor('black');
  });

  doc.moveDown(0.5);
  if (job.result) {
    doc.fontSize(12).text('Order Result:', { underline: true });
    doc.moveDown(0.25);
    doc.fontSize(10).text(`Order ID: ${job.result.order_id}`);
    if (job.result.supplier_name) doc.text(`Supplier: ${job.result.supplier_name}`);
    if (job.result.total_usd !== undefined) doc.text(`Total (USD): $${job.result.total_usd}`);
    if (job.result.explanation) {
      doc.moveDown(0.2);
      doc.fontSize(9).fillColor('gray').text(job.result.explanation);
      doc.fillColor('black');
    }
  }

  doc.moveDown(0.5);
  doc.fontSize(9).fillColor('gray').text('Generated by PackRoute Agent');
  doc.end();

  stream.on('finish', () => {
    console.log(`Receipt written to ${out}`);
  });
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
